spring:
  application:
    name: spring-App-eureka-client

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
  instance:
    preferIpAddress: true